/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Dimension;
import java.awt.TextField;
import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import model.Person.Person;
import javax.swing.*;  
import model.Address.City;
import model.Address.Community;
import model.Address.House;
import model.Address.HouseDirectory;
import model.Person.PersonDirectory;

/**
 *
 * @author Dell
 */
public class CreateProfile extends javax.swing.JPanel {

    /**
     * Creates new form CreateProfile
     */
    PersonDirectory modelPersonObj;
    HouseDirectory houseDirecObj;
    ArrayList<String> cityNames;
    public CreateProfile(PersonDirectory modelPersonObj, 
                        ArrayList<String> cityNames,
                        HouseDirectory houseDirecObj
                        ) {
        initComponents();
        this.modelPersonObj = modelPersonObj;
        this.houseDirecObj = houseDirecObj;
        cityNames = cityNames;
        comboCity.setModel(new DefaultComboBoxModel<String>(cityNames.toArray(new String[0])));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        basePanel = new javax.swing.JPanel();
        txtLastName = new javax.swing.JTextField();
        lbHouseNumber = new javax.swing.JLabel();
        txtHouseNumber = new javax.swing.JTextField();
        lbCommunityName = new javax.swing.JLabel();
        comboCommunity = new javax.swing.JComboBox<>();
        lbCity = new javax.swing.JLabel();
        comboCity = new javax.swing.JComboBox<>();
        lbFirstName = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        lbLastName = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtStreetName = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        lblSex = new javax.swing.JLabel();
        comboSex = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        jScrollPane1.setBorder(null);

        basePanel.setBackground(new java.awt.Color(102, 153, 255));

        txtLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastNameActionPerformed(evt);
            }
        });

        lbHouseNumber.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbHouseNumber.setText("House Number :");

        txtHouseNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHouseNumberActionPerformed(evt);
            }
        });
        txtHouseNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtHouseNumberKeyReleased(evt);
            }
        });

        lbCommunityName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbCommunityName.setText("Community : ");

        comboCommunity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "American", "Asian" }));

        lbCity.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbCity.setText("City : ");

        comboCity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Boston", "Waltham" }));

        lbFirstName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbFirstName.setText("First Name : ");

        txtFirstName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFirstNameFocusLost(evt);
            }
        });
        txtFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstNameActionPerformed(evt);
            }
        });

        lbLastName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbLastName.setText("Last Name :");

        btnSubmit.setBackground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("Save");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Street Name :");

        txtStreetName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStreetNameActionPerformed(evt);
            }
        });

        lblTitle.setBackground(new java.awt.Color(102, 255, 255));
        lblTitle.setFont(new java.awt.Font("Sitka Small", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Create Person Profile");
        lblTitle.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblSex.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSex.setText("Sex :");

        comboSex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        javax.swing.GroupLayout basePanelLayout = new javax.swing.GroupLayout(basePanel);
        basePanel.setLayout(basePanelLayout);
        basePanelLayout.setHorizontalGroup(
            basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basePanelLayout.createSequentialGroup()
                .addGroup(basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, basePanelLayout.createSequentialGroup()
                        .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(basePanelLayout.createSequentialGroup()
                        .addGroup(basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(basePanelLayout.createSequentialGroup()
                                .addGap(303, 303, 303)
                                .addGroup(basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbLastName)
                                    .addComponent(lbCommunityName)
                                    .addComponent(lbHouseNumber)
                                    .addComponent(lblSex)
                                    .addComponent(jLabel1)
                                    .addComponent(lbCity)))
                            .addGroup(basePanelLayout.createSequentialGroup()
                                .addGap(136, 136, 136)
                                .addComponent(lbFirstName)))
                        .addGap(29, 29, 29)
                        .addGroup(basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtLastName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtFirstName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(comboCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboSex, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHouseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStreetName, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboCity, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 316, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, basePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSubmit)
                .addGap(366, 366, 366))
        );
        basePanelLayout.setVerticalGroup(
            basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basePanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle)
                    .addComponent(jLabel2))
                .addGap(22, 22, 22)
                .addGroup(basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbFirstName)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLastName)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSex)
                    .addComponent(comboSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCommunityName)
                    .addComponent(comboCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbHouseNumber)
                    .addComponent(txtHouseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtStreetName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCity)
                    .addComponent(comboCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSubmit)
                .addContainerGap(379, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(basePanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtStreetNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStreetNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStreetNameActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        boolean firstNameValidation = this.validateName(txtFirstName);
        boolean lastNameValidation = this.validateName(txtLastName);
        boolean houseNumberValidation = this.validateHouseNumber(txtHouseNumber);
        boolean streetNameValidation = this.validateName(txtStreetName);
        JTextField[] textFieldArray = {txtFirstName, txtLastName,
            txtHouseNumber, txtStreetName};
        if (firstNameValidation && lastNameValidation && houseNumberValidation
            && streetNameValidation){
            String firstName = txtFirstName.getText().toString();
            String lastName = txtLastName.getText().toString();
            int houseNumber = Integer.parseInt(txtHouseNumber.getText().toString());
            String streetName = txtStreetName.getText().toString();
            String cityName = comboCity.getSelectedItem().toString();
            String communityName = comboCommunity.getSelectedItem().toString();
            House hObj = new House(houseNumber, streetName,
                new Community(communityName), new City(cityName));

            Person p = new Person(firstName, lastName, hObj);
            System.out.println(p.getPersonId());
            hObj.addPerson(p);
            this.houseDirecObj.addNewHouse(hObj);
            this.modelPersonObj.addPerson(p);
            JOptionPane.showMessageDialog(this, "Added the Person Successfully");

            //Reset text fields to empty when Save button is clicked
//        txtSerialNo.setText("");
//        txtBrand.setText("");
//        txtModelNo.setText("");
//        jDateChooserMaintCerti.setDate(null);
//        txtMfgYear.setText("");
//        txtSeatNo.setText("");
//        txtCity.setText("");
  // }
            this.resetTextFields(textFieldArray);
           
        }
        else{
            String errorMessage = String.format("First Name Validation : %s \n" +
                "Last Name Validation : %s \n" + "HouseNumber Validaiton : %s",
                firstNameValidation, lastNameValidation, houseNumberValidation);

            UIManager.put("OptionPane.minimumSize",new Dimension(100,200));
            JOptionPane.showMessageDialog(this, errorMessage);
            this.resetTextFields(textFieldArray);
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void txtFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNameActionPerformed

    private void txtFirstNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFirstNameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNameFocusLost

    private void txtHouseNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHouseNumberKeyReleased
        // TODO add your handling code here:
        try {
            Integer.parseInt(txtHouseNumber.getText());
            if(txtHouseNumber.getText().length() > 4){
                JOptionPane.showMessageDialog(this, "House Number cannot be more than 4 digits.");
            }
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "House Number cannot be more than 4 digits.");
        }
    }//GEN-LAST:event_txtHouseNumberKeyReleased

    private void txtHouseNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHouseNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHouseNumberActionPerformed

    private void txtLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel basePanel;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> comboCity;
    private javax.swing.JComboBox<String> comboCommunity;
    private javax.swing.JComboBox<String> comboSex;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCity;
    private javax.swing.JLabel lbCommunityName;
    private javax.swing.JLabel lbFirstName;
    private javax.swing.JLabel lbHouseNumber;
    private javax.swing.JLabel lbLastName;
    private javax.swing.JLabel lblSex;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtHouseNumber;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtStreetName;
    // End of variables declaration//GEN-END:variables
    
    private boolean validateName(JTextField name){
        String enteredText = name.getText();
        if(name.getText().isEmpty()){
            return false;
        }
        else{
            Pattern namePattern = Pattern.compile("[A-Za-z\\s-.]+");
            Matcher nameMatcher = namePattern.matcher(enteredText);
            if(nameMatcher.matches()){
                return true;
            }
        }
        return false;
    } 

    private boolean validateHouseNumber(JTextField pk){
        String enteredText = pk.getText();
        if(pk.getText().isEmpty()){
            return false;
        }
        else{
            Pattern namePattern = Pattern.compile("[0-9A-Za-z\\s-,.]+");
            Matcher nameMatcher = namePattern.matcher(enteredText);
            if(nameMatcher.matches()){
                return true;
            }
        }
        return false;
    } 
    
    private void resetTextFields(JTextField[] arr){
        for(JTextField reset : arr){
            reset.setText("");
        }
    }
}
