/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Patient.Patient;
import model.Patient.PatientDirectory;
import model.Person.Person;

/**
 *
 * @author Dell
 */
public class ViewPatient extends javax.swing.JPanel {

    /**
     * Creates new form ViewPatient
     */
    PatientDirectory patientDirec;
    public ViewPatient(PatientDirectory patientDirec) {
        initComponents();
        this.patientDirec = patientDirec;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPatientDetails = new javax.swing.JTable();
        btnViewPatientDetails = new javax.swing.JButton();
        comboCommunity = new javax.swing.JComboBox<>();
        lbCommunityName = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 153, 255));

        tblPatientDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "First Name", "Last Name", "Person Id", "Last Visit Date", "Age", "Blood Pressure", "Community", "City"
            }
        ));
        jScrollPane1.setViewportView(tblPatientDetails);

        btnViewPatientDetails.setBackground(new java.awt.Color(255, 255, 255));
        btnViewPatientDetails.setText("View Patients");
        btnViewPatientDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPatientDetailsActionPerformed(evt);
            }
        });

        comboCommunity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "American", "Asian" }));
        comboCommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCommunityActionPerformed(evt);
            }
        });

        lbCommunityName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbCommunityName.setText("Select Community:");

        lblTitle.setBackground(new java.awt.Color(102, 255, 255));
        lblTitle.setFont(new java.awt.Font("Sitka Small", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("View Patient Details");
        lblTitle.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbCommunityName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(440, 440, 440)
                        .addComponent(btnViewPatientDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 761, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCommunityName)
                    .addComponent(btnViewPatientDetails))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(267, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewPatientDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPatientDetailsActionPerformed
        // TODO add your handling code here:
        this.populatePatientTable();
    }//GEN-LAST:event_btnViewPatientDetailsActionPerformed

    private void comboCommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCommunityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboCommunityActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnViewPatientDetails;
    private javax.swing.JComboBox<String> comboCommunity;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCommunityName;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblPatientDetails;
    // End of variables declaration//GEN-END:variables
    private void populatePatientTable(){
        DefaultTableModel model = (DefaultTableModel) tblPatientDetails.getModel();
        model.setRowCount(0);
        
        this.patientDirec.populatePatients();
       String communityName =  comboCommunity.getSelectedItem().toString();
       
        for(Patient patientModel : this.patientDirec.getPatientDirectory()){
            if(!communityName.equals(patientModel.getCommunityName())){
            continue;
            }
            System.out.println(patientModel);
            Object[] row = new Object[8];
            row[0] = patientModel;
            row[1] = patientModel.getLastName();
            row[2] = String.valueOf(patientModel.getPersonId());
//            Calendar cal = new GregorianCalendar();
//        int month = cal.get(Calendar.MONTH);
//        int year = cal.get(Calendar.YEAR);
//        int day = cal.get(Calendar.DAY_OF_MONTH);
//        int second = cal.get(Calendar.SECOND);
//        int minute = cal.get(Calendar.MINUTE);
//        int hour = cal.get(Calendar.HOUR);
        
       // txtLastUpdated.setText((month+1)+"/"+day+"/"+year+ " " + hour+":"+(minute)+":"+second+" Hrs" );
            row[3] = patientModel.encounter.getEncounteredDate();
            row[4] = patientModel.encounter.getAge();
            row[5] = patientModel.encounter.getBloodPressure();
            row[6] = patientModel.getCommunityName();
            row[7] = patientModel.getCityName();
            model.addRow(row);
        }
    }
        
    }
